CREFloresEPlantas/Areas/Admin/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CREFloresEPlantas.Data;
using CREFloresEPlantas.Models;


namespace CREFloresEPlantas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProdutoController : Controller
    {
        private ApplicationDbContext _db;
        //serve para guardar imagens no root > images, se houver tempo meto em blobstorage
        private IHostingEnvironment _he;
        public ProdutoController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }
        public IActionResult Index()
        {
            return View(_db.Produtos.Include(c=>c.TiposProdutos).Include(f=>f.SpecialTag).ToList());
        }
        [HttpPost]
        public IActionResult Index(double? baixoP, double? altoP)
        {
            var produtos = _db.Produtos.Include(c => c.TiposProdutos).Include(c => c.SpecialTag).Where(c=>c.Preco>=baixoP&&c.Preco<=altoP).ToList();
            if (baixoP==null || altoP==null)
            {
                produtos = _db.Produtos.Include(c => c.TiposProdutos).Include(c => c.SpecialTag).ToList();
            }
            return View(produtos);
        }
        //Create - Criar Produto
        public IActionResult Create()
        {
            ViewData["tipoProdutoId"] = new SelectList(_db.TiposProdutos.ToList(), "Id", "TipoProduto");
            ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "Nome");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Produtos produto,IFormFile imagem)
        {
            if (ModelState.IsValid)
            {
                var procurarProduto = _db.Produtos.FirstOrDefault(c => c.Nome == produto.Nome);
                if (procurarProduto != null)
                {
                    ViewBag.message = "Este produto já existe.";
                    ViewData["tipoProdutoId"] = new SelectList(_db.TiposProdutos.ToList(), "Id", "TipoProduto");
                    ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "Nome");
                    return View(produto);
                }

                if (imagem!=null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(imagem.FileName));
                    await imagem.CopyToAsync(new FileStream(name, FileMode.Create));
                    produto.Imagem = "Images/" + imagem.FileName;
                }
                if (imagem==null)
                {
                    produto.Imagem = "Images/SemImagem.png";
                }
                _db.Produtos.Add(produto);
                await _db.SaveChangesAsync();
                TempData["save"] = "Sucesso!";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(produto);
        }
        //Edit - Editar Produto
        public ActionResult Edit(int? id)
        {
            ViewData["tipoProdutoId"] = new SelectList(_db.TiposProdutos.ToList(), "Id", "TipoProduto");
            ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "Nome");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Produtos.Include(c => c.TiposProdutos).Include(c => c.SpecialTag).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Produtos produto, IFormFile imagem)
        {
            if (ModelState.IsValid)
            {
                if (imagem != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(imagem.FileName));
                    await imagem.CopyToAsync(new FileStream(name, FileMode.Create));
                    produto.Imagem = "Images/" + imagem.FileName;
                }
                if (imagem == null)
                {
                    produto.Imagem = "Images/SemImagem.png";
                }
                _db.Produtos.Update(produto);
                await _db.SaveChangesAsync();
                TempData["save"] = "Sucesso!";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(produto);
        }

        //Details - Detalhes Produto
        public ActionResult Details(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var product = _db.Produtos.Include(c => c.TiposProdutos).Include(c => c.SpecialTag).FirstOrDefault(c=>c.Id==id);
            if (product==null)
            {
                return NotFound();
            }
            return View(product);
        }

        //Delete - Apagar produtos
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var produto = _db.Produtos.Include(c=>c.SpecialTag).Include(c => c.TiposProdutos).Where(c => c.Id == id).FirstOrDefault();
            if(produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var produto = _db.Produtos.FirstOrDefault(c => c.Id == id);
            if (produto == null)
            {
                return NotFound();
            }
            _db.Produtos.Remove(produto);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

CREFloresEPlantas/Areas/Admin/Controllers/SpecialTagController.cs
using CREFloresEPlantas.Data;
using CREFloresEPlantas.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CREFloresEPlantas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagController : Controller
    {
        private ApplicationDbContext _db;
        public SpecialTagController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {

            return View(_db.SpecialTags.ToList());
        }
        //Create - Criar tag
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTag specialTag)
        {
            if (ModelState.IsValid)
            {
                _db.SpecialTags.Add(specialTag);
                await _db.SaveChangesAsync();
                TempData["save"] = "Sucesso!";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTag);
        }
        //Edit - Editar tag
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTag specialTag)
        {
            if (ModelState.IsValid)
            {
                _db.Update(specialTag);
                await _db.SaveChangesAsync();
                TempData["save"] = "Sucesso!";
                return RedirectToAction(nameof(Index));
            }

            return View(specialTag);
        }

        //Details - Detalhes do tag

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(SpecialTag specialTag)
        {
            return RedirectToAction(nameof(Index));

        }
        //Delete - apagar tags
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialTag = _db.SpecialTags.Find(id);
            if (specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, SpecialTag specialTag)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (id != specialTag.Id)
            {
                return NotFound();
            }

            var specialTags = _db.SpecialTags.Find(id);
            if (specialTags == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(specialTags);
                await _db.SaveChangesAsync();
                TempData["save"] = "Apagado!";
                return RedirectToAction(nameof(Index));
            }

            return View(specialTag);
        }
    }
}

CREFloresEPlantas/Areas/Admin/Controllers/TiposProdutosController.cs
using CREFloresEPlantas.Data;
using CREFloresEPlantas.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CREFloresEPlantas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TiposProdutosController : Controller
    {
        private ApplicationDbContext _db;
        public TiposProdutosController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //var data = _db.TiposProdutos.ToList();
            return View(_db.TiposProdutos.ToList());
        }

        //Create - Criar Tipo de Produto
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Create(TiposProdutos tiposProdutos)
        {
            if(ModelState.IsValid)
            {
                _db.TiposProdutos.Add(tiposProdutos);
                await _db.SaveChangesAsync();
                TempData["save"]="Sucesso!";
                return RedirectToAction(actionName:nameof(Index));
            }
            return View(tiposProdutos);
        }
        //Edit - Editar Tipo de Produto
        public ActionResult Edit(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var tipoProduto = _db.TiposProdutos.Find(id);
            if (tipoProduto==null)
            {
                return NotFound();
            }
            return View(tipoProduto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TiposProdutos tiposProdutos)
        {
            if (ModelState.IsValid)
            {
                _db.TiposProdutos.Update(tiposProdutos);
                await _db.SaveChangesAsync();
                TempData["save"] = "Sucesso!";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(tiposProdutos);
        }
        //Details - Detalhes do Tipo de Produto
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var tipoProduto = _db.TiposProdutos.Find(id);
            if (tipoProduto == null)
            {
                return NotFound();
            }
            return View(tipoProduto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(TiposProdutos tiposProdutos)
        {
            return RedirectToAction(actionName: nameof(Index));
        }

        //Delete - Apagar Tipo de Produto
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var tipoProduto = _db.TiposProdutos.Find(id);
            if (tipoProduto == null)
            {
                return NotFound();
            }
            return View(tipoProduto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, TiposProdutos tiposProdutos)
        {
            if (id==null)
            {
                return NotFound();
            }
            if (id!=tiposProdutos.Id)
            {
                return NotFound();
            }
            var tipoProduto = _db.TiposProdutos.Find(id);

            if (tipoProduto==null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(tipoProduto);
                await _db.SaveChangesAsync();
                TempData["save"] = "Apagado!";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(tiposProdutos);
        }
    }
}

CREFloresEPlantas/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model"><i class="far fa-edit"></i></a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></a>
    </div>
</td>

CREFloresEPlantas/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using CREFloresEPlantas.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    int count = 0;
    List<Produtos> produtos = HttpContextAccessor.HttpContext.Session.Get<List<Produtos>>("produtos");
    if (produtos == null)
    {
        produtos = new List<Produtos>();
    }
    count = produtos.Count();

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Flores&Plantas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CREFloresEPlantas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="TiposProdutos" asp-action="Index">Tipos de Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Cliente" asp-controller="Home" asp-action="Cart">
                                <i class="fas fa-shopping-cart"> </i>
                                (@count)
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CREFloresEPlantas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>

CREFloresEPlantas/Views/Shared/_TagPageButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="SpecialTag" class="btn btn-primary" asp-route-id="@Model"><i class="far fa-edit"></i></a>
        <a asp-action="Details" asp-controller="SpecialTag" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" asp-controller="SpecialTag" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></a>
    </div>
</td>